# Deployment for packagemanage service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: package-manage-server
spec:
  selector:
    matchLabels:
      comp: package-manage
  template:
    metadata:
      labels:
        comp: package-manage
    spec:
      containers:
        - name: pkg-manage-server
          image: opensourceway/packagemanage:v2.0
          env:
          - name: OBS_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: package-manage-server-secret
                key: obs_account
          - name: OBS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: package-manage-server-secret
                key: obs_password
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: package-manage-server-secret
                key: git_token
          - name: EMAIL_SENDER
            valueFrom:
              secretKeyRef:
                name: package-manage-server-secret
                key: email_sender
          - name: EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: package-manage-server-secret
                key: email_password
          volumeMounts:
            - mountPath: /etc/database
              name: database-volume
            - mountPath: /etc/pkgship/conf.yaml
              name: pkgmanage-config-volume
              subPath: conf.yaml
            - mountPath: /etc/pkgship/package.ini
              name: pkgmanage-config-volume
              subPath: package.ini
            - mountPath: /etc/pkgship/timed_task.yaml
              name: pkgmanage-config-volume
              subPath: timed_task.yaml
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
          command:
            - /bin/sh
            - -c
            - |
              chmod +x /etc/auto_setup.sh
              bash /etc/auto_setup.sh
              sleep infinity
      volumes:
        - name: pkgmanage-config-volume
          configMap:
            name: packagemanage-config
        - name: database-volume
          persistentVolumeClaim:
            claimName: openeuler-pkgship-db-volume

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: package-manage-web
spec:
  selector:
    matchLabels:
      comp: package-manage-web
  template:
    metadata:
      labels:
        comp: package-manage-web
    spec:
      containers:
        - name: pkgmanagewebui
          image: opensourceway/pkgmanageweb:v1.0
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi

